
/*
Auto-generated by CVXPYgen on November 18, 2024 at 14:09:49.
Content: Declarations for Python binding with pybind11.
*/

// User-defined parameters
struct CPG_Params_cpp_t {
    std::array<double, 13> param5;
    std::array<double, 169> param1;
    std::array<double, 52> param2;
};

// Flags for updated user-defined parameters
struct CPG_Updated_cpp_t {
    bool param5;
    bool param1;
    bool param2;
};

// Primal solution
struct CPG_Prim_cpp_t {
    std::array<double, 143> var4;
    std::array<double, 40> var3;
};

// Dual solution
struct CPG_Dual_cpp_t {
    std::array<double, 13> d0;
    std::array<double, 13> d1;
    std::array<double, 4> d2;
    std::array<double, 4> d3;
    std::array<double, 13> d4;
    std::array<double, 4> d5;
    std::array<double, 4> d6;
    std::array<double, 13> d7;
    std::array<double, 4> d8;
    std::array<double, 4> d9;
    std::array<double, 13> d10;
    std::array<double, 4> d11;
    std::array<double, 4> d12;
    std::array<double, 13> d13;
    std::array<double, 4> d14;
    std::array<double, 4> d15;
    std::array<double, 13> d16;
    std::array<double, 4> d17;
    std::array<double, 4> d18;
    std::array<double, 13> d19;
    std::array<double, 4> d20;
    std::array<double, 4> d21;
    std::array<double, 13> d22;
    std::array<double, 4> d23;
    std::array<double, 4> d24;
    std::array<double, 13> d25;
    std::array<double, 4> d26;
    std::array<double, 4> d27;
    std::array<double, 13> d28;
    std::array<double, 4> d29;
    std::array<double, 4> d30;
};

// Solver information
struct CPG_Info_cpp_t {
    double obj_val;
    int iter;
    char* status;
    double pri_res;
    double dua_res;
    double time;
};

// Solution and solver information
struct CPG_Result_cpp_t {
    CPG_Prim_cpp_t prim;
    CPG_Dual_cpp_t dual;
    CPG_Info_cpp_t info;
};

// Main solve function
CPG_Result_cpp_t solve_cpp(struct CPG_Updated_cpp_t& CPG_Updated_cpp, struct CPG_Params_cpp_t& CPG_Params_cpp);
